openapi: 3.0.0

info:
 title: My First Docs Application
 description: Learning About the writting documention with swagger
 version: 1.0.0
 contact: 
  email: Khariprasath30@gmail.com
  



servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: Localhost Url
    variables:
      version:
         enum:  # giving the option for your varibles
          - v1
          - v2
         default: v1
      protocol:
          enum:
           - http
          default: http


components:
  securitySchemes:
   cookieAuth:
     type: apiKey
     in: cookie
     name: token
   BearerAuth:
     type: http
     scheme: bearer


paths:
  /signup:
    post:
      tags:
        - User
      summary: Add a new user to the database
      
      requestBody:
        required: true
        content: 
          multipart/form-data:
              schema:
                  type: object
                  properties:
                      name:
                        type: string
                        required: true
                      email:
                        type: string
                        required: true
                      password:
                        type: number
                        required: true
                      photo:
                          in: formData
                          description: The uploaded file data
                          type: file
                          format: binary


      responses:
        200:
          description: getting user 
          content:
            multipart/from-data:
              schema:
                  type: boolean
                  
                    
        400:
            description: Bad Request
        500:
            description: Internal Server Error

